[package]
name = "gpui-client-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpui = { path = "/Users/rnatarajan/Documents/Coding/others/zed-main/crates/gpui" }

